---
title: "Animal Game extra plotss"
author: "Dan Yurovsky"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    number_sections: no
    theme: lumen
    toc: no
    toc_float: no
  pdf_document:
    toc: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, warning=FALSE, show = F}
library(tidyverse)
library(forcats)
library(knitr)
library(tidytext)
library(readxl)
library(tidyboot)
library(stringr)
library(janitor)
library(here)
library(ggthemes)
library(lme4)
library(lmerTest)
library(directlabels)
library(ggrepel)
library(feather)

opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, 
               error = FALSE, cache = TRUE, tidy = FALSE)


theme_set(theme_classic(base_size = 20))
```


```{r masur_plot}
masur_data <- data_frame(age = c(10, 13, 17, 21), 
           novel_mean= c(97, 93, 92, 97), 
           comprehended_mean = c(NA, 92, 87, 76), 
           familiar_mean = c(NA, 90, 78, 58),
           novel_sd = c(8, 16, 13, 11),
           comprehended_sd = c(NA, 15, 25, 24),
           familiar_sd = c(NA, 8, 27, 24),
           n = c(17, 20, 17, 17 )) %>%
  gather(type, value, novel_mean:familiar_sd) %>%
  separate(type, into = c("type", "measure")) %>%
  mutate(value = value / 100) %>%
  spread(measure, value) %>%
  mutate(se = sd / sqrt(n)) %>%
  rowwise() %>%
  mutate(ci_upper = min(mean + 1.96 * se, 1),
         ci_lower = max(mean - 1.96 * se, 0)) %>%
  select(age, n, type, mean, ci_upper, ci_lower) %>%
  mutate(type = factor(type, levels = c("comprehended", "familiar", "novel")))

jpeg("masur_plot.jpeg", width = 6, height = 4, units = "in", res = 600)
ggplot(masur_data, aes(x = age, y = mean, ymin = ci_lower, ymax = ci_upper,
       color = type, label = type)) + 
  geom_pointrange(position = position_dodge(.25)) +
  geom_smooth(method = "lm", se = F) +
  geom_dl(method = list(dl.trans(x=x +.2), "last.qp", cex=1)) +
  scale_color_ptol() + 
  scale_x_continuous(name = "age (months)", limits = c(10, 26), 
                     breaks = c(10, 13, 17, 21)) +
  scale_y_continuous(name = "prop. labeled in first mention") +
  theme(legend.position = "none")
dev.off()

jpeg("masur_plot.jpeg", width = 6, height = 4, units = "in", res = 600)
ggplot(masur_data, aes(x = age, y = mean, ymin = ci_lower, ymax = ci_upper,
       color = type, label = type)) + 
  geom_pointrange(position = position_dodge(.5)) +
  geom_smooth(method = "lm", se = F) +
  geom_dl(method = list(dl.trans(x=x +.5), "last.qp", cex=1.2)) +
  scale_color_ptol() + 
  scale_x_continuous(name = "age (months)", limits = c(10, 26), 
                     breaks = c(10, 13, 17, 21)) +
  scale_y_continuous(name = "labeled on first mention") +
  theme(legend.position = "none")
dev.off()

```

```{r wordbank_plot, eval = F}
items <- read_csv(here("analysis/item_trajectory_table.csv")) %>%
  select(-skip) %>%
  gather(animal, prop, dog, cow) %>%
  group_by(animal, age) %>%
  summarise(prop = mean(prop, na.rm = T))


#jpeg("wordbank_plot.jpg", width = 6, height = 4, units = "in", res = 600)
ggplot(items, aes(x = age, y = prop, color = animal, label = animal)) +
  geom_point() + 
  geom_smooth(se = F) +
  geom_dl(method = list(dl.trans(x=x +.5), "last.qp", cex=1.2)) +
  geom_hline(aes(yintercept = .5), lty = 2, size = 1) + 
  scale_color_ptol() + 
  scale_x_continuous(name = "age (months)", limits = c(8, 32), 
                     breaks = seq(8, 30, 4)) +
  scale_y_continuous(name = "prop. producing", limits = c(0, 1)) +
  theme(legend.position = "none")
#dev.off()
```
