---
title: "Animal Game Transcripts"
author: "Ashley Leung, Alex Tunkel, and Dan Yurovsky"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    number_sections: no
    theme: lumen
    toc: no
    toc_float: no
  pdf_document:
    toc: no
---
```{r, message=FALSE, warning=FALSE, show = F}
library(tidyverse)
library(forcats)
library(knitr)
library(tidytext)
library(readxl)
library(tidyboot)
library(stringr)
library(janitor)
library(here)
library(ggthemes)
library(lme4)
library(lmerTest)
library(directlabels)
library(ggrepel)
library(feather)

opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, 
               error = FALSE, cache = TRUE, tidy = FALSE)


theme_set(theme_classic(base_size = 20))
```


```{r masu_plot}
masur_data <- data_frame(age = c(10, 13, 17, 21), 
           novel_mean= c(97, 93, 92, 97), 
           comprehended_mean = c(NA, 92, 87, 76), 
           familiar_mean = c(NA, 90, 78, 58),
           novel_sd = c(8, 16, 13, 11),
           comprehended_sd = c(NA, 15, 25, 24),
           familiar_sd = c(NA, 8, 27, 24),
           n = c(17, 20, 17, 17 )) %>%
  gather(type, value, novel_mean:familiar_sd) %>%
  separate(type, into = c("type", "measure")) %>%
  mutate(value = value / 100) %>%
  spread(measure, value) %>%
  mutate(se = sd / sqrt(n)) %>%
  rowwise() %>%
  mutate(ci_upper = min(mean + 1.96 * se, 1),
         ci_lower = max(mean - 1.96 * se, 0)) %>%
  select(age, n, type, mean, ci_upper, ci_lower) %>%
  mutate(type = factor(type, levels = c("comprehended", "familiar", "novel")))

jpeg("masur_plot.jpeg", width = 6, height = 4, units = "in", res = 600)
ggplot(masur_data, aes(x = age, y = mean, ymin = ci_lower, ymax = ci_upper,
       color = type, label = type)) + 
  geom_pointrange(position = position_dodge(.25)) +
  geom_smooth(method = "lm", se = F) +
  geom_dl(method = list(dl.trans(x=x +.2), "last.qp", cex=1)) +
  scale_color_ptol() + 
  scale_x_continuous(name = "age (months)", limits = c(10, 26), 
                     breaks = c(10, 13, 17, 21)) +
  scale_y_continuous(name = "prop. labeled in first mention") +
  theme(legend.position = "none")
dev.off()

jpeg("masur_plot.jpeg", width = 6, height = 4, units = "in", res = 600)
ggplot(masur_data, aes(x = age, y = mean, ymin = ci_lower, ymax = ci_upper,
       color = type, label = type)) + 
  geom_pointrange(position = position_dodge(.5)) +
  geom_smooth(method = "lm", se = F) +
  geom_dl(method = list(dl.trans(x=x +.5), "last.qp", cex=1.2)) +
  scale_color_ptol() + 
  scale_x_continuous(name = "age (months)", limits = c(10, 26), 
                     breaks = c(10, 13, 17, 21)) +
  scale_y_continuous(name = "labeled on first mention") +
  theme(legend.position = "none")
dev.off()

```

```{r wordbank_plot, eval = F}
items <- read_csv(here("analysis/item_trajectory_table.csv")) %>%
  select(-skip) %>%
  gather(animal, prop, dog, cow) %>%
  group_by(animal, age) %>%
  summarise(prop = mean(prop, na.rm = T))


#jpeg("wordbank_plot.jpg", width = 6, height = 4, units = "in", res = 600)
ggplot(items, aes(x = age, y = prop, color = animal, label = animal)) +
  geom_point() + 
  geom_smooth(se = F) +
  geom_dl(method = list(dl.trans(x=x +.5), "last.qp", cex=1.2)) +
  geom_hline(aes(yintercept = .5), lty = 2, size = 1) + 
  scale_color_ptol() + 
  scale_x_continuous(name = "age (months)", limits = c(8, 32), 
                     breaks = seq(8, 30, 4)) +
  scale_y_continuous(name = "prop. producing", limits = c(0, 1)) +
  theme(legend.position = "none")
#dev.off()
```

Read in vocab data

```{r read_data, message=F}
qualtrics_data <- read_csv(here("raw_data/qualtrics_data.csv")) %>%
  slice(3:nrow(.)) %>%
  clean_names()

qualtrics_ids <- read_csv(here("raw_data/qualtrics_ids.csv")) %>%
  clean_names()

survey1 <- read_csv(here("raw_data/survey_link1.csv"))
survey2 <- read_csv(here("raw_data/survey_link2.csv"))
survey3 <- read_csv(here("raw_data/survey_link3.csv"))

vocab_data <- bind_rows(survey1, survey2, survey3) %>%
  clean_names() %>%
  filter(!is.na(response_id)) %>%
  left_join(qualtrics_data, by = "response_id") %>%
  select(link, q1) %>%
  left_join(qualtrics_ids, by = "link") %>%
  select(q1, response_id, number) %>%
  rename(video_id = response_id, subj = number) %>%
  filter(!is.na(subj))

```

Demographics
```{r demographics}
demo_data <- read_csv(here("raw_data/animalgame_demo.csv"))
```

Munge vocab data
```{r munge_vocab}
tidy_vocab <- vocab_data %>%
  unnest_tokens(word, q1) %>% 
  mutate(understands = T) %>%
  select(-video_id) %>%
  complete(subj, word, fill = list(understands = F)) %>%
  left_join(select(vocab_data, -q1), by = "subj")
```
Read in response data
```{r read_response}
child_response <- read_csv(here("raw_data/animalgame_data.csv")) %>%
  filter(!subj %in% c("xx", "Twst", "Test", "test"))

missing_data <- read_csv(here("raw_data/animalgame_missing.csv"))

filled_data <- bind_rows(child_response, missing_data)

response_data <- left_join(vocab_data, filled_data, by = "subj") %>%
  mutate(game_trial = trial_type != "practice") %>%
  arrange(subj, game_trial, trial_num) %>%
  group_by(subj) %>%
  mutate(trial_num = 1:n(),
         correct = correct == "Y")


#write_csv(response_data, "wrong_trialnums.csv")

```

Read in transcript data
```{r munge}
transcripts <- list.files(here("raw_data/qcoded"), "*.csv", full.names = T)


read_transcript <- function(file) {

  print(file)
  
  transcript <- read_csv(file) %>%
    #mutate(id = parse_number(basename(file))) %>%
    mutate(id = str_split(file, "[//.]")[[1]] %>% tail(2) %>% head(1),
           id = gsub("q", "", id)) %>%
    #remove_empty("cols") %>%
    clean_names()
    
    # Pull out either parent or child's data
    pull_data <- function(person) {
      transcript %>%
        select(starts_with(person), descriptors:num_superordinate) %>%
        select_all(~gsub(paste0(person,"_"), "", .x)) %>%
        select_all(~gsub("utterance_", "", .x)) %>%
        mutate(person = person) %>%
        mutate(id = first(transcript$id))
    
    }
  
  # Tidy up
  bind_rows(pull_data("parent")) %>%
    mutate(target = gsub("\\.", "", target) %>% tolower) %>%
    mutate(utterance = str_trim(utterance))
}

tidy_data <- map(transcripts, read_transcript) %>%
  bind_rows()

targets <- tidy_data %>%
  filter(!is.na(target), target != "n/a") %>%
  distinct(target, .keep_all = T) %>%
  select(id, target) %>%  pull()

practice_targets <- c("artichoke", "apple") 
```

The unique targets were: `r targets`

```{r word_difficulty}

word_difficulty <- tidy_vocab %>%
  filter(word %in% targets, video_id %in% tidy_data$id) %>%
  group_by(word) %>%
  tidyboot_mean(understands) %>%
  rename(understands = empirical_stat) %>%
  arrange(desc(understands)) %>%
  rename(difficulty = understands) %>%
  select(-mean)

tidy_vocab %>%
  select(subj, word, understands) %>%
  filter(word %in% targets) %>%
  mutate(type = if_else(word %in% c("apple", "artichoke"), "practice",
         if_else(word %in% c("cat", "dog", "bird", "cow", "fish", "duck", "horse", "elephant"),
                 "early", "late")))%>%
  left_join(word_difficulty) %>%
  write_feather(here("data/word_difficulty.feather"))

#word_difficulty %>%
#  mutate(type = if_else(word %in% c("apple", "artichoke"), "practice",
#         if_else(word %in% c("cat", "dog", "bird", "cow", "fish", "duck", "horse", "elephant"),
#                 "early", "late"))) %>%
#  write_feather(here("data/word_difficulty.feather"))


plotting_words <- word_difficulty %>%
  mutate(word = factor(word, levels = unique(word))) %>%
  rename(understands = difficulty)

#jpeg("word_diff.jpeg", width = 8, height = 6, units = "in", res = 600)
ggplot(plotting_words, aes(x = word, y = understands, ymin = ci_lower, 
                            ymax = ci_upper)) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5), 
        text = element_text(size = 20)) +
  geom_pointrange() +
  labs(y = "prop. parents report known", x = "") 
#dev.off()

##ascending order for prop. known

jpeg("word_diff_ascend.jpeg", width = 10, height = 8, units = "in", res = 600)
ggplot(plotting_words, aes(x = reorder(word, understands), y = understands, ymin = ci_lower, 
                            ymax = ci_upper)) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1), 
        text = element_text(size = 20)) +
  geom_pointrange() +
  labs(y = "Proportion of children reported knowing the word", x = "") 
dev.off()
```

Munge transcript data
```{r make_target_df}
trials <- tidy_data %>%
  group_by(id) %>%
  arrange(id, onset) %>%
  filter(target %in% targets) %>%
  mutate(new_trial = target != lag(target),
         new_trial = if_else(is.na(new_trial), TRUE, new_trial),
         trial = cumsum(new_trial)) %>%
  select(-new_trial)


# Selections per target--should be 2 for each target for each id
selects <- trials %>%
  filter(selection == "selects") %>%
  group_by(id, target) %>%
  summarise(n = n()) %>%
  filter(n != 2)

trial_targets <- trials %>%
  distinct(id, trial, target) %>%
  rename(trial_target = target)

# Trials per target, should be 2 for each id
trial_targets %>%
  group_by(id, trial_target) %>%
  summarise(n = n()) %>% 
  filter(n != 2)

parent_data <- tidy_data %>%
#  filter(id != "9261") %>%
  filter(person == "parent") %>%
  left_join(trials) %>%
  group_by(id) %>%
  fill(trial) %>%
  filter(!is.na(trial)) %>%
  group_by(id, trial) %>%
  mutate(selection = max(0, which(str_detect(selection, "selects")),
                             na.rm = T)) %>%
  mutate(phase = case_when(row_number() < selection ~ "pre",
                           row_number() == selection ~ "during",
                           T ~ "post") %>%
           factor(levels = c("pre", "during", "post"))) %>%
  left_join(trial_targets) %>%
 # filter(!is.na(target), !target %in% c("<target>", "n/a")) %>%
  group_by(id, trial_target) %>%
  mutate(appearance = factor(trial >= mean(trial))) %>%
  ungroup() %>%
  mutate(appearance = factor(appearance, labels = c("first", "second")),
         id = as.character(id))


target_data_gaps <- parent_data %>%
  mutate(length = str_count(utterance, " ") + 1,
         length = if_else(is.na(length), as.numeric(0), length)) %>%
  left_join(word_difficulty, by = c("target" = "word")) %>%
 # rename(difficulty = understands) %>%
  left_join(tidy_vocab, by = c("id" = "video_id", "trial_target" = "word")) %>%
 # filter(phase != "during") %>%
  group_by(phase, difficulty, understands, appearance, trial_target, id)

ids <- target_data_gaps %>%
  ungroup() %>%
  distinct(id, subj) %>%
  filter(!is.na(subj))

target_data <- target_data_gaps %>%
  select(-subj) %>%
  left_join(ids) %>%
  left_join(response_data, by = c("subj", "trial_target" = "target", "trial" = "trial_num")) %>%
  filter(trial_type != "practice")

target_data %>%
  ungroup() %>%
  select(subj, person, target, trial, phase, trial_target, appearance, length, difficulty, understands, correct, trial_type, game_trial) %>%
  write_feather(here("data/target_data.feather"))

```

```{r accuracy}
test_data <- target_data %>%
  ungroup() %>%
  filter(phase == "pre", !is.na(understands)) %>%
  group_by(id, trial_target, appearance, correct, 
         trial, difficulty, understands) %>%
  summarise(length = log(sum(length)),
            num_canonical = sum(!is.na(num_canonical)) > 0,
            num_descriptors = sum(!is.na(num_descriptors)) > 0,
            num_anaphoric = sum(!is.na(num_anaphoric)) > 0,
            num_comparison = sum(!is.na(num_comparison)) > 0,
            num_subordinate = sum(!is.na(num_subordinate)) > 0,
            num_superordinate = sum(!is.na(num_superordinate)) > 0) %>%
  rename(ease = difficulty) %>%
  write_feather(here("data/qual_data.feather"))

test_data %>%
    mutate(understands = factor(understands, levels = c(T,F), 
                              labels = c("Knows", "Doesn't Know"))) %>%
  glmer(correct ~ length * understands + appearance + trial + 
        (1|id) + (1|trial_target), 
      family = "binomial", 
      control = glmerControl(optimizer = "bobyqa"),
      data = .) %>%
  tidy() %>%
  filter(group == "fixed") 


test_data %>%
  ungroup() %>%
  mutate(understands = factor(understands, levels = c(T,F), 
                              labels = c("Knows", "Doesn't Know"))) %>%
  group_by(correct,  understands) %>%
  tidyboot_mean(length) %>%
  ggplot(aes(x = understands, y = empirical_stat, 
             ymin = ci_lower, ymax = ci_upper,
             color = correct)) + 
  geom_pointrange(position = position_dodge(.5))



# ggplot(test_data, aes(x = understands, y = correct)) +
#   facet_wrap(~ appearance) +
#   geom_point(alpha = .1)
# 
# cor.test(response_data_difficulty$mean, as.numeric(response_data_difficulty$correct),
#          use = "complete", method = "kendall")

```

```{r qual_coding}
tidy_test_data <- test_data %>%
  gather(measure, value, num_canonical, num_descriptors, num_comparison,
         num_subordinate, num_superordinate) %>%
  write_feather(here("data/qual_model.feather"))

models <- tidy_test_data %>%
  group_by(measure) %>%
  nest() %>%
  mutate(model = map(data, ~glmer(value ~ understands + appearance + length +
                      (1 |id), 
                      family = "binomial", data = .) %>% tidy())) %>%
  select(-data) %>%
  unnest() %>%
  filter(group == "fixed") %>%
  select(-group)
```

```{r qual-coding-plots}
jpeg("qual_plot.jpeg", width = 10, height = 8, units = "in", res = 600)
test_data %>%
  ungroup() %>%
  gather(measure, value, num_canonical, num_descriptors, num_comparison,
         num_subordinate, num_superordinate) %>%
  mutate(measure = case_when(
        measure == "num_canonical" ~ "Canonical label",
        measure == "num_descriptors" ~ "Descriptors",
        measure =="num_comparison" ~ "Comparison",
        measure =="num_subordinate" ~ "Subordinate category",
        measure =="num_superordinate" ~ "Superordinate category"))%>%
  mutate(understands = factor(understands, levels = c(T,F), 
                              labels = c("Knows", "Doesn't Know"))) %>%
  group_by(understands, measure) %>%
  tidyboot_mean(value) %>%
  ggplot(aes(x = understands, y = empirical_stat, 
             ymin = ci_lower, ymax = ci_upper, color = measure)) + 
  labs(x = "Parents' belief about animal word", y = "Proportion of trials") +
  facet_wrap(~measure, scales = "free") + 
  geom_pointrange(position = position_dodge(.5)) + 
  theme(legend.position = "none")
dev.off()

jpeg("qual_plot2.jpeg", width = 12, height = 4, units = "in", res = 600)
test_data %>%
  ungroup() %>%
  gather(measure, value, num_descriptors, num_comparison,
         num_superordinate) %>%
    mutate(measure = case_when(
        measure == "num_descriptors" ~ "Descriptors",
        measure =="num_comparison" ~ "Comparison",
        measure =="num_superordinate" ~ "Superordinate category"))%>%
  mutate(understands = factor(understands, levels = c(T,F), 
                              labels = c("Knows", "Doesn't Know"))) %>%
  group_by(understands, measure) %>%
  tidyboot_mean(value) %>%
  ggplot(aes(x = understands, y = empirical_stat, 
             ymin = ci_lower, ymax = ci_upper, color = measure)) + 
  labs(x = "Parents' belief about animal word", y = "Proportion of trials") +
  facet_wrap(~measure, scales = "free") + 
  geom_pointrange(position = position_dodge(.5)) + 
  theme(legend.position = "none")
dev.off()

test_data %>%
  ungroup() %>%
  gather(measure, value, num_canonical, num_descriptors, num_comparison,
         num_anaphoric, num_subordinate, num_superordinate) %>%
  mutate(measure = case_when(
    measure == "num_canonical" ~ "canonical words",
    measure == "num_descriptors" ~ "number of descriptors",
    T ~ measure)) %>%
  mutate(understands = factor(understands, levels = c(T,F), 
                              labels = c("Knows", "Doesn't Know"))) %>%
  mutate(appearance = factor(appearance)) %>%
  group_by(understands, appearance, measure) %>%
  tidyboot_mean(value) %>%
  ggplot(aes(x = understands, y = empirical_stat, 
             ymin = ci_lower, ymax = ci_upper, color = appearance)) + 
  #facet_grid(appearance ~ measure, scales = "free") +
  facet_wrap(~measure, scales = "free") + 
  geom_pointrange(position = position_dodge(.5))

```


```{r plot_lengths_aggregate}
target_data %>%
  filter(phase != "during") %>%
  summarise(length = sum(length)) %>%
  ggplot(aes(x = difficulty, y = log(length), color = phase)) + 
  facet_wrap(~ appearance) +
  geom_point() +
  geom_smooth(method = "glm", se = F) +
  scale_color_ptol()
```


```{r plot_lengths_pre}
plotting_data <- target_data %>%
  filter(phase == "pre", !is.na(difficulty)) %>%
  group_by(appearance, target, id) %>%
  summarise(length = log(sum(length))) %>%
  tidyboot_mean(length) %>%
  rename(length = empirical_stat,
         length_upper = ci_upper,
         length_lower = ci_lower) %>%
  select(-mean, -n) %>%
  left_join(word_difficulty, by = c("target" = "word")) %>%
  rename(understands_lower = ci_lower, understands_upper = ci_upper, 
         understands = difficulty) %>%
  mutate(plotting_appearance = factor(appearance, levels = c("first", "second"),
                                     labels = c("1st appearance",
                                                "2nd appearance")))


jpeg("length_facetted.jpeg", width = 8, height = 4, units = "in", res = 600)
ggplot(plotting_data, aes(x = understands, y = length, xmin = understands_lower,
                          xmax = understands_upper, ymin = length_lower,
                          ymax = length_upper, color = plotting_appearance,
                          label = target)) + 
  geom_smooth(method = "lm", se = F) +
  facet_wrap( ~ plotting_appearance) + 
  geom_pointrange()+ 
  geom_errorbarh() + 
  geom_label_repel() +
  scale_color_ptol() +
  theme(legend.position = "none") +
  labs(x = "prop. parents report known", 
       y = "log utterance length") 
dev.off()

jpeg("length_apperance.jpeg", width = 6, height = 4, units = "in", res = 600)
ggplot(plotting_data, aes(x = understands, y = length, xmin = understands_lower,
                          xmax = understands_upper, ymin = length_lower,
                          ymax = length_upper, color = plotting_appearance)) + 
  geom_smooth(method = "lm", se = F) +
  geom_pointrange(alpha = .2)+ 
  geom_errorbarh(alpha = .2) + 
  scale_color_ptol() +
  theme(legend.position = "none") +
  labs(x = "prop. parents report known", 
       y = "log utterance length") 
dev.off()

jpeg("continuous_length.jpeg", width = 6.2, height = 6, units = "in", res = 600)
target_data %>%
  filter(phase == "pre", !is.na(difficulty)) %>%
  summarise(length = sum(length)) %>%
  ungroup() %>%
  ggplot(aes(x = difficulty, y = log(length+1))) + 
  geom_jitter(alpha = .1) +
  geom_smooth(method = "glm", se = T) +
  scale_color_ptol() +
  labs(x = "Proportion of children who know the word (parent report)", y = "Log Utterance length") + 
  geom_hline(aes(yintercept = 2), lty = 2) +
  scale_y_continuous()
dev.off()

continuous_plot_data <- target_data %>%
  filter(phase == "pre", !is.na(difficulty)) %>%
  group_by(target, id) %>%
  summarise(length = sum(length)) %>%
  tidyboot_mean(length) %>%
  rename(length = empirical_stat,
         length_upper = ci_upper,
         length_lower = ci_lower) %>%
  select(-mean, -n) %>%
  left_join(word_difficulty, by = c("target" = "word")) %>%
  rename(understands_lower = ci_lower, understands_upper = ci_upper, 
         understands = difficulty) %>%
  mutate(plotting_target = if_else(target %in% c("squirrel", "cat", "swan"),
                                   target, as.character(NA)))

jpeg("length_continuous.jpeg", width = 8, height = 5, units = "in", res = 600)
ggplot(continuous_plot_data, aes(x = understands, y = length, xmin = understands_lower,
                          xmax = understands_upper, ymin = length_lower,
                          ymax = length_upper,
                          label = plotting_target)) + 
  geom_smooth(method = "lm", se = F, color = "black") +
  geom_pointrange()+ 
  geom_errorbarh() + 
  geom_label_repel() +
  theme(legend.position = "none") +
  labs(x = "Proportion of children reported knowing target word", 
       y = "Parents' words produced") 
dev.off()
```


```{r plot_lengths_personal}
mean_data <- target_data %>%
  filter(phase == "pre", !is.na(understands)) %>%
  group_by(appearance, understands, id, target) %>%
  summarise(length = sum(length)) %>%
  summarise(length = mean(log(length))) %>%
  tidyboot_mean(length) %>%
  mutate(understands = factor(understands, 
                              labels = c("unknown", "known")),
         plotting_appearance = factor(appearance, 
                                      levels = c("first", "second"),
                                      labels = c("1st appearance", 
                                                 "2nd appearance")))


jpeg("belief_plot.jpeg", width = 6, height = 4, units = "in", res = 600)
ggplot(mean_data,
       aes(x = understands, y = empirical_stat, 
           ymin = ci_lower, ymax = ci_upper, color = plotting_appearance)) + 
  facet_wrap(~ plotting_appearance) +
  geom_pointrange(position = position_dodge(.5)) +
  scale_color_ptol() +
  labs(x = "Parent's belief", y = "Log Utterance length") +
  theme(legend.position = "none")
dev.off()
```

```{r first_utterance}
mean_data <- target_data %>%
  filter(phase != "during") %>%
  group_by(phase, appearance, understands, id, trial_target) %>%
  arrange(id, appearance, phase, trial_target, onset) %>%
  summarise(length = first(length)) %>%
  summarise(length = mean(log(length+1), na.rm = T)) %>%
  tidyboot_mean(length)

ggplot(filter(mean_data, !is.na(understands)),
       aes(x = understands, y = empirical_stat, 
           ymin = ci_lower, ymax = ci_upper, color = phase)) + 
  facet_wrap(~ appearance) +
  geom_pointrange(position = position_dodge(.5)) +
  scale_color_ptol()

```


```{r lag_analysis}
#pdf("lag_data.pdf", width = 6, height = 4)
target_data %>%
  ungroup() %>%
  mutate(understands = factor(understands, labels = c("unknown", "known"))) %>%
  filter(!id %in% c("10397", "8787")) %>%
#  mutate(phase = factor(as.character(phase), levels = c("pre", "post"))) %>%
  group_by(id, phase, understands, trial_target, appearance, correct) %>%
  summarise(length = sum(length)) %>%
  ungroup() %>%
  complete(nesting(id, trial_target, understands,  correct,  appearance), phase,
           fill = list(length = 0)) %>%
  arrange(id, phase, understands, trial_target,appearance, correct) %>%
  group_by(id, phase, understands, trial_target) %>%
  mutate(lag_correct = lag(correct)) %>%
  filter(appearance == "second", phase != "during") %>%
  group_by(phase, understands, lag_correct, id, trial_target) %>%
  summarise(length = sum(length, na.rm = T)) %>%
  summarise(length = mean(log(length+1), na.rm = T)) %>%
  filter(!is.na(understands)) %>%
  tidyboot_mean(length) %>%
  ggplot(aes(x = lag_correct, y = empirical_stat, 
           ymin = ci_lower, ymax = ci_upper, color = phase)) + 
  facet_wrap(~ understands) +
  geom_pointrange(position = position_dodge(.5)) +
  scale_color_ptol()
#dev.off()


lag_data <- target_data %>%
  filter(phase == "pre", !is.na(understands)) %>%
  ungroup() %>%
  mutate(understands = factor(understands, 
                              labels = c("child doesn't know", "child knows"))) %>%
  mutate(correct = factor(correct, levels = c(TRUE, FALSE), 
                          labels = c("correct", "incorrect"))) %>%
  group_by(id, phase, understands, target, appearance, correct) %>%
  summarise(length = sum(length)) %>%
  ungroup() %>%
  complete(nesting(id, target, understands,  correct,  appearance),
           fill = list(length = 0)) %>%
  arrange(id, understands, target,appearance, correct) %>%
  group_by(id, understands, target) %>%
  mutate(lag_correct = lag(correct)) %>%
  filter(appearance == "second", !is.na(lag_correct)) %>%
  group_by(understands, lag_correct, id, target) %>%
  summarise(length = sum(length, na.rm = T)) %>%
  summarise(length = mean(log(length), na.rm = T)) %>%
  tidyboot_mean(length)

jpeg("lag_correct.jpeg", width = 6, height = 4, units = "in", res = 600)
ggplot(lag_data, aes(x = lag_correct, y = empirical_stat, 
           ymin = ci_lower, ymax = ci_upper, color = understands)) + 
  facet_wrap(~ understands) +
  geom_pointrange(position = position_dodge(.5), show.legend = F) +
  labs(x ="Child's previous response", y = "Log utterance length") +
  scale_color_ptol()+
  theme_classic(base_size = 20)
dev.off()
```


```{r write_demos}
target_data %>%
  ungroup() %>%
  distinct(subj) %>%
  left_join(qualtrics_ids, by = c("subj"="number")) %>%
  left_join(demo_data, by = c("response_id"="id")) %>%
  select(subj, age, gender, race, mom_ed) %>%
  mutate(age_months = floor(age / 30.5),
         age_extra_days = floor(age - (age_months * 30.5)),
         age_years = age/365,
         gender = factor(gender, levels = c("f", "m"), 
                         labels = c("female", "male")),
         race = as.factor(race),
         mom_ed = as.factor(mom_ed)) %>%
  left_join(tidy_vocab %>% group_by(subj) %>% 
              summarise(vocab = sum(understands)), by = "subj") %>%
  select(-age) %>%
  write_feather(here("data/demos.feather"))

```

```{r language}
target_data %>% 
  ungroup() %>%
  filter(phase == "pre", trial_type != "practice", !is.na(understands)) %>% 
  select(understands, id, utterance) %>% 
  mutate(length = nchar(utterance)) %>%
  mutate(length = log(length)) %>%
  group_by(id) %>%
  mutate(length = scale(length)) %>%
  group_by(utterance) %>%
  ggplot(aes(x = length, color = understands)) +
  geom_density()
```


```{r model}
target_data %>%
  ungroup() %>%
  filter(!is.na(difficulty), phase != "during") %>%
  mutate(difficulty = 1 - difficulty) %>%
  group_by(difficulty, understands, correct, trial, phase, appearance, trial_target, id) %>%
  summarise(length = sum(length)) %>%
  lmer(log(length) ~ difficulty + appearance + difficulty * phase + difficulty* correct + trial +
         difficulty* understands + (1|trial_target) + (1|id), data = .) %>%
  summary()

```
